/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.koushik;

/**
 *
 * @author ramvi
 */
public class splash1 extends javax.swing.JFrame {

    /**
     * Creates new form splash1
     */
    public splash1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingbar = new javax.swing.JProgressBar();
        load = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        PIC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(loadingbar);
        loadingbar.setBounds(10, 360, 220, 20);

        load.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        load.setForeground(new java.awt.Color(255, 255, 255));
        load.setText("%");
        getContentPane().add(load);
        load.setBounds(190, 330, 80, 30);

        text.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("Loading............");
        getContentPane().add(text);
        text.setBounds(10, 330, 90, 30);

        PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/koushik/fRONT.jpg"))); // NOI18N
        PIC.setText("jLabel1");
        PIC.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(PIC);
        PIC.setBounds(0, -10, 800, 620);

        setSize(new java.awt.Dimension(800, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PIC;
    public javax.swing.JLabel load;
    public javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
