/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.koushik;

/**
 *
 * @author user
 */
public class ur06b1 extends javax.swing.JFrame {

    /**
     * Creates new form ur06b1
     */
    public ur06b1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        rb11 = new javax.swing.JRadioButton();
        rb22 = new javax.swing.JRadioButton();
        rb33 = new javax.swing.JRadioButton();
        rb44 = new javax.swing.JRadioButton();
        rb55 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rb11.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rb11);
        rb11.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb11.setText("LOCATION");
        rb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb11ActionPerformed(evt);
            }
        });
        getContentPane().add(rb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 53, -1, -1));

        rb22.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(rb22);
        rb22.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb22.setText("CAMPUS");
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });
        getContentPane().add(rb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, 81, -1));

        rb33.setBackground(new java.awt.Color(130, 102, 62));
        buttonGroup1.add(rb33);
        rb33.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb33.setText("STUDENTS");
        rb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb33ActionPerformed(evt);
            }
        });
        getContentPane().add(rb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 135, -1, -1));

        rb44.setBackground(new java.awt.Color(154, 106, 57));
        buttonGroup1.add(rb44);
        rb44.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb44.setText("MOTTO");
        rb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb44ActionPerformed(evt);
            }
        });
        getContentPane().add(rb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 176, 81, -1));

        rb55.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rb55);
        rb55.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb55.setText("WEBSITE");
        rb55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb55ActionPerformed(evt);
            }
        });
        getContentPane().add(rb55, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 217, 81, -1));

        t2.setBackground(new java.awt.Color(204, 204, 204));
        t2.setColumns(20);
        t2.setRows(5);
        jScrollPane1.setViewportView(t2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 53, -1, 187));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/koushik/pexels-photo-326311.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ur03 a =new ur03();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb11ActionPerformed
         if(rb11.isSelected())
         {
         t2.setText("MIT ROAD\nRADHA NAGAR\nCHROMPET\nCHENNAI\nTAMIL NADU-600044\nINDIA ");}
    }//GEN-LAST:event_rb11ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
        if(rb22.isSelected())
        {
         t2.setText("URBAN-200acers");
        }
    }//GEN-LAST:event_rb22ActionPerformed

    private void rb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb33ActionPerformed
       if(rb33.isSelected())
       {
       t2.setText("UNDERGRADUATES :2000(approx)\nPOSTGRADUATES :300(approx)\n");}
    }//GEN-LAST:event_rb33ActionPerformed

    private void rb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb44ActionPerformed
        if(rb44.isSelected())
        {
        t2.setText("IN THE SERVICE OF INDIA");}
        
    }//GEN-LAST:event_rb44ActionPerformed

    private void rb55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb55ActionPerformed
        if(rb55.isSelected())
        {
        t2.setText("http://WWW.mitindia.edu/");}
    }//GEN-LAST:event_rb55ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ur06b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ur06b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ur06b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ur06b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ur06b1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JRadioButton rb33;
    private javax.swing.JRadioButton rb44;
    private javax.swing.JRadioButton rb55;
    private javax.swing.JTextArea t2;
    // End of variables declaration//GEN-END:variables
}
