/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.koushik;

/**
 *
 * @author user
 */
public class ur07c1 extends javax.swing.JFrame {

    /**
     * Creates new form ur07c1
     */
    public ur07c1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        rb111 = new javax.swing.JRadioButton();
        rb222 = new javax.swing.JRadioButton();
        rb333 = new javax.swing.JRadioButton();
        rb444 = new javax.swing.JRadioButton();
        rb555 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rb111.setBackground(new java.awt.Color(108, 72, 0));
        buttonGroup1.add(rb111);
        rb111.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb111.setForeground(new java.awt.Color(255, 255, 255));
        rb111.setText("LOCATION");
        rb111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb111ActionPerformed(evt);
            }
        });
        getContentPane().add(rb111, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 41, 90, -1));

        rb222.setBackground(new java.awt.Color(100, 67, 2));
        buttonGroup1.add(rb222);
        rb222.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb222.setForeground(new java.awt.Color(255, 255, 255));
        rb222.setText("CAMPUS");
        rb222.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb222ActionPerformed(evt);
            }
        });
        getContentPane().add(rb222, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 82, 90, -1));

        rb333.setBackground(new java.awt.Color(97, 64, 0));
        buttonGroup1.add(rb333);
        rb333.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb333.setForeground(new java.awt.Color(255, 255, 255));
        rb333.setText("STUDENTS");
        rb333.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb333ActionPerformed(evt);
            }
        });
        getContentPane().add(rb333, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 123, 90, -1));

        rb444.setBackground(new java.awt.Color(95, 63, 0));
        buttonGroup1.add(rb444);
        rb444.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb444.setForeground(new java.awt.Color(255, 255, 255));
        rb444.setText("MOTTO");
        rb444.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb444ActionPerformed(evt);
            }
        });
        getContentPane().add(rb444, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 164, 90, -1));

        rb555.setBackground(new java.awt.Color(87, 58, 0));
        buttonGroup1.add(rb555);
        rb555.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        rb555.setForeground(new java.awt.Color(255, 255, 255));
        rb555.setText("WEBSITE");
        rb555.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb555ActionPerformed(evt);
            }
        });
        getContentPane().add(rb555, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 205, 90, -1));

        ta3.setBackground(new java.awt.Color(153, 153, 153));
        ta3.setColumns(20);
        ta3.setRows(5);
        jScrollPane1.setViewportView(ta3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 41, -1, 187));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cse/koushik/images (34).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ur04 a =new ur04();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb111ActionPerformed
        if(rb111.isSelected())
        {
            ta3.setText("4,NH 45A,NEHRUNAGAR\nKARAIKAL\nPUDUCHERRY 609605\nINDIA");
        }
            
    }//GEN-LAST:event_rb111ActionPerformed

    private void rb222ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb222ActionPerformed
        if(rb222.isSelected())
        {
            ta3.setText("256acers");
        }
    }//GEN-LAST:event_rb222ActionPerformed

    private void rb333ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb333ActionPerformed
       if(rb333.isSelected())
       {
       ta3.setText("UNDERGRADUATES:1000\nPOSTGRADUATES:200");}
    }//GEN-LAST:event_rb333ActionPerformed

    private void rb444ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb444ActionPerformed
        if(rb444.isSelected())
        {
        ta3.setText("KARAIKAL TO BEST");}
            
    }//GEN-LAST:event_rb444ActionPerformed

    private void rb555ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb555ActionPerformed
        if(rb555.isSelected())
        {
        ta3.setText("http://WWW.nitpy.ac.in/");}
    }//GEN-LAST:event_rb555ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ur07c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ur07c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ur07c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ur07c1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ur07c1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb111;
    private javax.swing.JRadioButton rb222;
    private javax.swing.JRadioButton rb333;
    private javax.swing.JRadioButton rb444;
    private javax.swing.JRadioButton rb555;
    private javax.swing.JTextArea ta3;
    // End of variables declaration//GEN-END:variables
}
